# Generated by Django 4.2.3 on 2023-09-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.IntegerField()),
                ('conformpass', models.IntegerField()),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
