# Generated by Django 4.2.3 on 2023-09-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_logadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logadmin',
            options={'ordering': ('username',), 'verbose_name': 'login', 'verbose_name_plural': 'logins'},
        ),
    ]
