# Generated by Django 4.2.3 on 2023-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_logadmin_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logadmin',
            name='conformpass',
        ),
        migrations.AlterField(
            model_name='logadmin',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
