# Generated by Django 4.2.3 on 2023-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_logadmin_conformpass_alter_logadmin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadmin',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
