# Generated by Django 4.2.3 on 2023-09-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_logadmin_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logadmin',
            options={},
        ),
    ]
