# Generated by Django 4.2.3 on 2023-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_logadmin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadmin',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
