# Generated by Django 4.2.3 on 2023-09-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_logadmin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
